site_name: Kevinbot Core
site_author: Kevin Ahr
site_url: https://meowmeowahr.github.io/KevinbotV3-KiCAD/

theme:
  name: "material"
  language: en
  features:
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - navigation.indexes
  logo: images/logo_dark.png
  favicon: images/favicon.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: teal
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - mike:
  - search:
  - glightbox:

extra:
  version:
    provider: mike

nav:
  - index.md
  - diagram.md
  - harness.md
  - map.md
  - Assembly:
    - ftdi.md
  - software.md
  - gallery.md
  - develop.md
  - contributing.md
  - coc.md

repo_url: https://github.com/meowmeowahr/KevinbotV3-KiCAD
